#!/bin/bash

DIR_OBJ=/usr/local/bin

if [ "$(id -u)" == "0" ]; then
    echo "Permisos de ejecucion garantizados."
    echo "Comenzando la instalacion del script blockhosts.sh"
    if [ -d $DIR_OBJ ]; then
        echo "Directorio objetivo detectado: /usr/local/bin"
    else
        echo "Directorio objetivo no detectado."
        echo "Creando directorio: /usr/local/bin"
        mkdir $DIR_OBJ
    fi

    # Copiando y asignando permisos al script
    echo "Instalando archivos en /usr/local/bin"
    cp blockhosts.sh $DIR_OBJ/blockhosts.sh
    chmod +x $DIR_OBJ/blockhosts.sh
    echo "Instalacion completa. Ejecute: blockhosts.sh para empezar."
else
   echo "¡¡¡Para ejecutar el script debes usar sudo!!!"
fi

exit 0
